// SISIC Agent V7.9 Fix2 - Web Scoring Engine
const SISICEngine=(function(){
const D=SISIC_DATA;
function norm(s){let x=(s||'').toLowerCase().trim();x=x.replace(/[\r\n\t]/g,' ');
x=x.replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss');
x=x.replace(/Ä/g,'ae').replace(/Ö/g,'oe').replace(/Ü/g,'ue');
x=x.replace(/&amp;/g,' und ').replace(/&/g,' und ');
x=x.replace(/[\/\-_.,;:()\[\]{}'\"]/g,' ');x=x.replace(/\s+/g,' ').trim();return x;}
function cw(t,k){return(' '+t.toLowerCase()+' ').indexOf(' '+k.toLowerCase()+' ')>=0;}
function nvk(s){let x=(s||'').toLowerCase().trim();x=x.replace(/&/g,' and ').replace(/[\/\-_.,]/g,' ').replace(/\s+/g,' ').trim();return x;}
function sv(a,b){return nvk(a)===nvk(b);}
function stem(s){let x=(s||'').toLowerCase().trim();if(x.length>8){if(x.endsWith('en')||x.endsWith('er'))x=x.slice(0,-2);if(x.endsWith('n')||x.endsWith('e')||x.endsWith('s'))x=x.slice(0,-1);}return x;}
function scoreKw(txt,kw,w,t){if(!kw)return 0;if(cw(txt,kw)){let s=10+w;if((t||'').toUpperCase()==='PHRASE2')s+=4;return s;}if((t||'').toUpperCase()==='WORD'||!t){let st=stem(kw);if(st.length>=5&&(' '+txt).toLowerCase().indexOf(' '+st)>=0)return 4+(w*0.5);}return 0;}
function featPos(p){let t=' '+p.toLowerCase()+' ',best=0;for(const sig of[' inkl ',' inkl. ',' inklusive ',' integriert',' einschliesslich ',' samt ',' mit ']){let pos=t.indexOf(sig);if(pos>0&&(best===0||pos<best))best=pos;}return best;}
function featOnly(proj,cust,kw,fp){if(!fp)return false;let main=proj.substring(0,fp-1);if((' '+main+' ').toLowerCase().indexOf(' '+kw.toLowerCase()+' ')>=0)return false;if(kw.length>=5&&main.toLowerCase().indexOf(kw.toLowerCase())>=0)return false;if(cust.toLowerCase().indexOf(kw.toLowerCase())>=0)return false;return true;}
function isUniHosp(t){let l=t.toLowerCase();if(l.indexOf('universitaetsklinik')>=0)return true;if(l.indexOf('universitaetsmedizin')>=0)return true;if(l.indexOf('uniklinik')>=0)return true;if(l.indexOf('uni klinik')>=0)return true;if(l.indexOf('universit')>=0&&(l.indexOf('klinik')>=0||l.indexOf('medizin')>=0))return true;return false;}
function hcPrec(sisic,txt){let t=txt.toLowerCase(),isU=isUniHosp(txt),isH=cw(txt,'krankenhaus')||t.indexOf('klinik')>=0||cw(txt,'hospital'),hasM=t.indexOf('medizin')>=0;if(!isU&&t.indexOf('universit')>=0&&(isH||hasM))isU=true;if(sisic==='85300'){if(isU||hasM)return'86101';if(isH)return'86109';}if(sisic==='86101'||sisic==='86109'){if(isU||hasM)return'86101';if(isH)return'86109';}return sisic;}
function vertBySISIC(s){for(const m of D.mapping)if(m.u===s&&m.v)return m.v;for(const m of D.mapping)if(m.h===s&&m.v)return m.v;return'';}
function defSISIC(v){for(const c of D.config)if(c.v.toLowerCase().trim()===(v||'').toLowerCase().trim())return c.d;return'';}
function mapText(s,f){for(const m of D.mapping)if(m.u===s&&m[f])return m[f];for(const m of D.mapping)if(m.h===s&&m[f])return m[f];return'';}
function mapSales(s){return mapText(s,'sd');}
function mapDE(s){return mapText(s,'de');}
function cleanDisp(s){let x=(s||'').trim();if(x.length>6&&x.toLowerCase().endsWith('ern'))x=x.slice(0,-1);else if(x.length>5&&x.toLowerCase().endsWith('eln'))x=x.slice(0,-1);return x;}
function cleanHit(s){let x=(s||'').trim(),p=x.indexOf(' (');if(p>0)x=x.substring(0,p);return cleanDisp(x.trim());}
function shortHL(h,n){return h?h.split(';').slice(0,n).map(x=>cleanHit(x)).join(', '):''}
function shortC(h,n){return h?h.split(',').slice(0,n).map(x=>x.trim()).join(', '):''}
function cleanTrig(t){let x=norm(t);for(const w of[' gmbh',' ag',' kg',' mbh',' co'])x=x.split(w).join('');if(x.startsWith('g '))x=x.substring(2);return x.replace(/\s+/g,' ').trim();}
function enhance(sisic,v,h,base,txt){let t=txt;if(sisic.startsWith('2610')||(v||'').toLowerCase()==='semiconductor'){if(t.toLowerCase().indexOf('halbleiter')>=0||cw(t,'semiconductor')||cw(t,'wafer')||cw(t,'chip')||cw(t,'fab'))return'Halbleiterproduktion / Semiconductor-Kontext';}if((v||'').toLowerCase()==='food & beverage'||sisic==='10790'){if(cw(t,'oetker')||cw(t,'nahrungsmittel')||cw(t,'lebensmittel')||cw(t,'frischeprodukte'))return'Lebensmittelhersteller / Consumer Products';}if((v||'').toLowerCase()==='life sciences'||sisic.startsWith('325')){if(cw(t,'pfizer')||cw(t,'pharma')||cw(t,'manufacturing')||cw(t,'biotech'))return'Pharma- / Life-Sciences-Unternehmen';}if((v||'').toLowerCase()==='healthcare'){if(cw(t,'universitaetsmedizin')||cw(t,'klinikum')||cw(t,'medizin'))return'Gesundheitswesen / Klinikum / medizinischer Kontext';}if((v||'').toLowerCase()==='investment properties'){if(cw(t,'union investment')||cw(t,'real estate'))return'Immobilienbewirtschaftung / Real Estate';}if(sisic==='27200'){if(cw(t,'batterie')||cw(t,'batteriespeicher'))return'Batterieproduktion / Energiespeicher-Kontext';}return base;}
function salesReason(typ,trig,ziel){let ct=cleanTrig(trig);if(typ==='company')return ct?'Kunde klar identifiziert ('+ct+')':'Kunde klar identifiziert';const map={'Aerospace & Defense':'Kunde der Verteidigungsindustrie zugeordnet ('+ct+')','Healthcare':'Gesundheitswesen \u2013 Klinikum / medizinischer Kontext erkannt','Life Sciences':'Pharma-/Life-Sciences-Unternehmen erkannt ('+ct+')','Food & Beverage':'Unternehmen aus Lebensmittelbranche erkannt','Data Center':'Projekt im IT-/Rechenzentrumsumfeld','Higher Education':'Projekt im Hochschul-/Forschungsumfeld','Investment Properties':'Projekt im Immobilienumfeld'};return map[ziel]||'Projekt einem Branchensegment zugeordnet';}
function fmtMain(sisic,v,h){let t=shortHL(h,3);return v?'Zuordnung basiert auf Branche '+v+' | Erkannt: '+t:'Zuordnung basiert auf erkannten Begriffen | Erkannt: '+t;}
function bldResult(sisic,av,ar,v,h,txt){let ms=mapSales(sisic),md=mapDE(sisic),ch=ms||md||fmtMain(sisic,v,h);ch=enhance(sisic,v,h,ch,txt);return(av&&ar)?ar+' | '+ch:ch;}
function bldAlt(sisic,h,txt){let ms=mapSales(sisic),md=mapDE(sisic),v=vertBySISIC(sisic),ch=ms||md||('Weitere m\u00f6gliche Zuordnung (Erkannt: '+shortHL(h,2)+')');return(ms||md)?ch:enhance(sisic,v,h,ch,txt);}
function bldDirect(sisic,ar,txt,ct){let ms=mapSales(sisic),md=mapDE(sisic),v=vertBySISIC(sisic),ch=ms||md||ar;ch=enhance(sisic,v,'',ch,txt);return ar?ar+' | '+ch:ch;}
function bldVertFB(sisic,ar,txt){let ms=mapSales(sisic),md=mapDE(sisic),v=vertBySISIC(sisic),ch=ms||md||ar;ch=enhance(sisic,v,'',ch,txt);return ar?ar+' | '+ch:ch;}
function bldFB(sisic,v,h,txt){let ms=mapSales(sisic),md=mapDE(sisic),ch=ms||md||('SISIC-Vorschlag auf Basis generischer Keywords (Segment: '+v+' | Erkannt: '+shortC(h,3)+')');ch=enhance(sisic,v,h,ch,txt);if(ch.indexOf('Treffer:')>=0)return ch;return'Branche: '+v+' | '+ch+' | Basis: '+shortC(h,3);}
function bldFBAlt(sisic,v,h,txt){let ms=mapSales(sisic),md=mapDE(sisic),ch=ms||md||('Alternative aus Segment '+v+' (Erkannt: '+shortC(h,2)+')');if(ms||md)return ch;ch=enhance(sisic,v,h,ch,txt);return ch.toLowerCase().indexOf('alternative')>=0?ch:'Alternative Branche: '+v+' | '+ch;}
function calcConf(s1,s2,hadAV){if(hadAV){if(s1>=10)return.95;if(s1>=5)return.9;if(s1>=2)return.85;return.8;}if(s1>=10&&s1-s2>=3)return.9;if(s1>=5)return.8;if(s1>=2)return.75;if(s1>0)return.7;return 0;}
function calcFBConf(bs,hc){if(bs>=3||hc>=3)return.85;if(bs>=2||hc===2)return.8;if(bs>0)return.75;return 0;}
function confLabel(v){if(v>=.9)return'SEHR SICHER';if(v>=.8)return'SICHER';if(v>=.7)return'PR\u00dcFEN';if(v>0)return'UNSICHER';return'KEIN TREFFER';}
function cntCsv(s){return s?s.split(',').filter(x=>x.trim()).length:0;}
function aliasDecision(txt,proj,cust){let aS='',aV='',aR='',aHits='',bcS=0,bvS=0,bcT='',bvT='';for(const a of D.aliases){let trg=norm(a.tr);if(!trg||!cw(txt,trg))continue;switch(a.ty.toLowerCase()){case'company':if(a.w>=bcS){bcS=a.w;aS=a.ta;bcT=trg;}aHits+=(aHits?', ':'')+trg;break;case'company_vertical':case'generic':if(a.w>=bvS){bvS=a.w;aV=a.ta;bvT=trg;}aHits+=(aHits?', ':'')+trg;break;}}
if(aV.toLowerCase()==='higher education'){let tl=txt.toLowerCase(),cl=cust.toLowerCase();if(tl.indexOf('klinik')>=0||tl.indexOf('medizin')>=0||cl.indexOf('medizin')>=0||tl.indexOf('hospital')>=0){aV='Healthcare';bvT='klinik/medizin';}}
if(aS==='85300'){let tl=txt.toLowerCase();if(tl.indexOf('klinik')>=0||tl.indexOf('medizin')>=0||tl.indexOf('hospital')>=0){aS='86101';aR='Gesundheitswesen - Universit\u00e4tsklinikum / medizinischer Kontext erkannt';}}
if(!aS&&!aV){if(isUniHosp(txt)||isUniHosp(cust)){aS='86101';aR='Gesundheitswesen - Universit\u00e4tsklinikum / medizinischer Kontext erkannt';}else if(cw(txt,'krankenhaus')||cw(txt,'hospital')||cw(txt,'klinikum')){aS='86109';aR='Gesundheitswesen - Krankenhaus / Klinik erkannt';}}
let aScore=Math.max(bcS,bvS);if(aS)aR=salesReason('company',bcT,aS);else if(aV)aR=salesReason('generic',bvT,aV);return{aS,aV,aScore,aR,aHits};}
function fbTop3(txt,av){let ds={},dh={};for(const kw of D.fallbackKw){let k=norm(kw.k),v=kw.v.trim(),w=kw.w||1;if(!k||!v)continue;if(av&&!sv(v,av))continue;if(cw(txt,k)){if(ds[v]){ds[v]+=w>0?w:1;dh[v]+=', '+k;}else{ds[v]=w>0?w:1;dh[v]=k;}}}let sorted=Object.keys(ds).sort((a,b)=>ds[b]-ds[a]);return{v1:sorted[0]||'',s1:ds[sorted[0]]||0,h1:dh[sorted[0]]||'',v2:sorted[1]||'',s2:ds[sorted[1]]||0,h2:dh[sorted[1]]||'',v3:sorted[2]||'',s3:ds[sorted[2]]||0,h3:dh[sorted[2]]||''};}
function compAlt(cust){if(cw(cust,'umformtechnik')||cw(cust,'hirschvogel')||cw(cust,'forging')||cw(cust,'metal'))return{s:'25910',r:'Alternative aus Kundenkontext: Metallumformung / Forging / Pressing'};if(cw(cust,'automotive supplier')||cw(cust,'zulieferer'))return{s:'25910',r:'Alternative aus Kundenkontext: Automotive-Zulieferer / Metallverarbeitung'};return null;}
function applyCA(res,main,cust,proj){let a=compAlt(cust);if(!a||a.s===main)return;if(!res.alt1Code){res.alt1Code=a.s;res.alt1Reason=a.r;}else if(res.alt1Code!==a.s&&!res.alt2Code){res.alt2Code=a.s;res.alt2Reason=a.r;}}
function fillAlts(res,main,txt){if(res.alt1Code&&res.alt2Code)return;let fb=fbTop3(txt,'');let vs=[fb.v1,fb.v2,fb.v3],hs=[fb.h1,fb.h2,fb.h3];for(let i=0;i<3;i++){let s=defSISIC(vs[i]);if(!s||s===main||s===res.alt1Code||s===res.alt2Code)continue;if(!res.alt1Code){res.alt1Code=s;res.alt1Reason=bldFBAlt(s,vs[i],hs[i],txt);}else if(!res.alt2Code){res.alt2Code=s;res.alt2Reason=bldFBAlt(s,vs[i],hs[i],txt);}else break;}}
function computeRow(proj,cust,contr){let pN=norm(proj||''),cN=norm((cust||'')+' '+(contr||'')),txt=(pN+' '+cN).trim();let R={sisic:'',confidence:0,label:'',reason:'',alt1Code:'',alt1Reason:'',alt2Code:'',alt2Reason:'',vertical:''};if(!txt)return R;let fp=featPos(pN),al=aliasDecision(txt,pN,cN);
if(al.aS){let s=hcPrec(al.aS,txt);R.sisic=s;R.confidence=.95;R.label='SEHR SICHER';R.vertical=vertBySISIC(s);R.reason=bldDirect(s,al.aR,txt,cN);applyCA(R,s,cN,pN);fillAlts(R,s,txt);return R;}
let sd={},hd={},vd={};for(const kw of D.keywords){let si=kw.s.trim(),k=norm(kw.k),w=kw.w||0,t=kw.t||'';if(!si||!k)continue;let v=vertBySISIC(si),as=scoreKw(txt,k,w,t);if(as>0){if(featOnly(pN,cN,k,fp))as*=0.3;if(!al.aV||!v||sv(v,al.aV)||as>=10){if(sd[si]){sd[si]+=as;hd[si]+='; '+k+' ('+as.toFixed(1)+')';}else{sd[si]=as;hd[si]=k+' ('+as.toFixed(1)+')';}if(!vd[si])vd[si]=v;}}}
if(Object.keys(sd).length>0){let sorted=Object.keys(sd).sort((a,b)=>sd[b]-sd[a]);let t1=sorted[0]||'',t2=sorted[1]||'',t3=sorted[2]||'',s1=sd[t1]||0,s2=sd[t2]||0;let cf=calcConf(s1,s2,!!al.aV);t1=hcPrec(t1,txt);R.sisic=t1;R.confidence=cf;R.label=confLabel(cf);R.vertical=vertBySISIC(t1);R.reason=bldResult(t1,al.aV,al.aR,vd[t1]||'',hd[t1]||'',txt);if(t2){R.alt1Code=t2;R.alt1Reason=bldAlt(t2,hd[t2]||'',txt);}if(t3){R.alt2Code=t3;R.alt2Reason=bldAlt(t3,hd[t3]||'',txt);}applyCA(R,t1,cN,pN);fillAlts(R,t1,txt);return R;}
let fb=fbTop3(txt,al.aV),fs1=defSISIC(fb.v1),fs2=defSISIC(fb.v2),fs3=defSISIC(fb.v3);if(fs1){let fc=calcFBConf(fb.s1,cntCsv(fb.h1));fs1=hcPrec(fs1,txt);R.sisic=fs1;R.confidence=fc;R.label=confLabel(fc);R.vertical=fb.v1;R.reason=bldFB(fs1,fb.v1,fb.h1,txt);if(fs2){R.alt1Code=fs2;R.alt1Reason=bldFBAlt(fs2,fb.v2,fb.h2,txt);}if(fs3){R.alt2Code=fs3;R.alt2Reason=bldFBAlt(fs3,fb.v3,fb.h3,txt);}applyCA(R,fs1,cN,pN);fillAlts(R,fs1,txt);return R;}
if(al.aV){let ds=defSISIC(al.aV);if(ds){ds=hcPrec(ds,txt);R.sisic=ds;R.confidence=.75;R.label=confLabel(.75);R.vertical=al.aV;R.reason=bldVertFB(ds,al.aR,txt);applyCA(R,ds,cN,pN);fillAlts(R,ds,txt);return R;}}
R.label='Kein Treffer';R.reason='Keine passenden Keywords gefunden.';return R;}
return{computeRow,confLabel};})();
